### ISSUE TITLE
OpenAdaptxt SDK and libkpt.a

### ISSUE THREAD

**Issue by gh1232008** [k3a/OctopusKeyboard#2]
Hi,I have developed a Keyboard for iOS 8,which used your library,but it can't compile successed.In your word,libkpt.a should be possible to compile it for arm64,but the Xcode is still warning me with "missing required architecture x86_64 in file",how can I resolve this problem,can you give me some suggestions,thank you very much.

**Comment by insist159** [comment]
I have encountered this problem

**Comment by massimopiazza** [comment]
Was anyone able to integrate this library within an iOS 8 Custom Keyboard?

**Comment by k3a** [comment]
Guys from www.crimsonkeyboard.com integrated Adaptxt in their iOS8 keyboard but they said they licenced a paid version due to 64bit support.

**Comment by massimopiazza** [comment]
Thanks for the quick response, I also contacted them and I’m waiting for the informations about pricing.

Massimo Piazza

> Il giorno 09/mar/2015, alle ore 23:44, K3A notifications@github.com ha scritto:
> 
> Guys from www.crimsonkeyboard.com integrated Adaptxt in their iOS8 keyboard but they said they licenced a paid version due to 64bit support.
>

**Comment by hoangthanhdoan** [comment]
Hi all, How to get it? Could you tell me know? Please!

**Comment by zxl777** [comment]
Anybody know the price ofAdaptxt  paid version ?

**Comment by gstream** [comment]
so Anybody used Adaptxt to iOS project ?

**Comment by k3a** [comment]
OpenAdaptxt is open-source (http://openadaptxt.sourceforge.net/) and you should be able to compile it as I was. I haven't done anything magical, no modifications to the code, just setting correct arch in the xcode project files. At that time there were no arm64 arch on iOS, though. 

If you encounter some problems with arm64 (as I heard some report from [Crimson Keyboard](https://crimsonkeyboard.com/) developer), you may have to contribute to the open-source code or purchase their paid license. You can contact them [http://www.adaptxt.com/contact/](here) and ask for pricing and conditions. 

Closing the issue.
